# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SongJiangMember' do

pod 'SDWebImage',               '~> 3.7.1'
pod 'TTTAttributedLabel',       '~> 1.10.0'
pod 'FMDB',                     '~> 2.2'
pod 'RESideMenu',               '= 4.0.6'
pod 'pop',                      '~> 1.0.5'
pod 'MBProgressHUD',            '~> 0.8'
pod 'iRate',                    '~> 1.10.2'
pod 'iVersion',                 '~> 1.10.6'
pod 'SevenSwitch',              '~> 1.3.0'
pod 'JSBadgeView',              '~> 1.3.2'
pod 'Masonry',                  '~> 0.5.3'
pod 'AFNetworking',             '~> 2.5.0'
pod 'Mantle',                   '~> 1.5.4'
pod 'BaiduMapAPI',              '~> 2.7.0'
pod 'AlipaySDK-2.0',            '~> 2.0.3'
pod 'SQLCipher',                '~> 3.1.0'

pod 'Reveal-iOS-SDK',           '1.0.3'

end

target 'SongJiangMemberTests' do

end

